name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *' # running once a day

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: chicagopolice.org sitemap changes tracker
      uses: actions/checkout@v3
    - name: Fetch latest data
      run: |-
        wget -e robots=off --user-agent="Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0" https://home.chicagopolice.org/wp-sitemap-posts-page-1.xml -O page-1.xml && wget -e robots=off --referer https://chicagopolice.org --user-agent="Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0" https://home.chicagopolice.org/wp-sitemap-posts-post-1.xml -O post-1.xml && wget -e robots=off --user-agent="Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0" https://home.chicagopolice.org/wp-sitemap-posts-post-2.xml -O post-2.xml && wget -e robots=off --user-agent="Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0" https://home.chicagopolice.org/wp-sitemap-posts-post-3.xml -O post-3.xml && wget -e robots=off --user-agent="Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0" https://home.chicagopolice.org/wp-sitemap-posts-draft_policy-1.xml -O draft_policy-1.xml && wget -e robots=off --user-agent="Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0" https://home.chicagopolice.org/wp-sitemap-taxonomies-category-1.xml -O taxonomies-category-1.xml && wget -e robots=off --user-agent="Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0" https://home.chicagopolice.org/wp-sitemap-taxonomies-post_tag-1.xml -O taxonomies-post_tag-1.xml && wget -e robots=off --user-agent="Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0" https://home.chicagopolice.org/wp-sitemap-taxonomies-post_format-1.xml -O taxonomies-post_format-1.xml && wget -e robots=off --user-agent="Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0" https://home.chicagopolice.org/wp-sitemap-taxonomies-media_notification_types-1.xml -O taxonomies-media_notification_types-1.xml && wget -e robots=off --user-agent="Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0" https://home.chicagopolice.org/wp-sitemap-users-1.xml -O users-1.xml
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
