name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *' # running once a day

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: chicagopolice.org sitemap changes tracker
      uses: actions/checkout@v3
    - name: Install chrome
      run: sudo apt install google-chrome-stable
    - uses: nanasess/setup-chromedriver@v1
    - run: |
       export DISPLAY=:99
       chromedriver --url-base=/wd/hub &
       sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: Fetch latest data
      run: python3 dump_xmls.py
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
